config/routes.rb
Rails.application.routes.draw do
  root 'plans#index'  
  
  resources :plans

  devise_for :users, :controllers => {:registrations => "registrations"}
  

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :term_courses
  has_many :terms, through: :term_courses
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :user
  has_many :terms
end

app/models/term.rb
class Term < ActiveRecord::Base
  belongs_to :plan
  has_many :term_courses
  has_many :courses, through: :term_courses
end

app/models/term_course.rb
class TermCourse < ActiveRecord::Base
  belongs_to :term
  belongs_to :course
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :plans
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.where(user_id: current_user.id )
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
    @terms = Term.where(plan_id: @plan.id)
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)
    @plan.user_id = current_user.id
    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:name, :user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:login, :email, :password, :password_confirmation)}
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/layouts/_header.html.erb
<header> 
<h1>Welcome to the Academic Planning Tool</h1>
<% if user_signed_in?%>
<h3>Welcome, <%= current_user.login %></h3>
<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
<% else %>
<%= link_to "Sign In", new_user_session_path, :method => :get %>
<%= link_to "Sign up", new_user_registration_path, :method => :get %>

<% end %>


</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Planner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>

<%= yield %>

</body>
</html>

app/views/plans/_form.html.erb
<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<h1>Listing plans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.name %></td>
        <td><%= link_to 'Show', plan %></td>
        <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
        <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plan', new_plan_path %>

app/views/plans/new.html.erb
<h1>New plan</h1>

<%= render 'form' %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plan.name %>
</p>

<div id="accordion">
	<% @plan.terms.each do |term| %>
		<h3><%= term.semester + ' ' + term.year.to_s %></h3>
		<div>
			<p>
			<%=  term.semester + ' ' + term.year.to_s %>
			</p>
		</div>
	<% end %>
</div>

<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>